const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavour')
const addValue = require('./7-mind-granante')
sayHi('suresh')
sayHi(names.peter)
sayHi(names.john)